package com.systembpm.system.modules.audit.domain;

public enum AuditAction {
    DOCUMENT_UPLOADED,
    DOCUMENT_METADATA_VIEWED,
    DOCUMENT_DOWNLOAD_REQUESTED,
    DOCUMENT_TAG_ADDED,
    DOCUMENT_TAG_REMOVED,
    DOCUMENT_EDITING_STARTED,
    DOCUMENT_EDITING_FINISHED,
    DOCUMENT_SAVED_FROM_ONLYOFFICE,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_LOCKED,
    DOCUMENT_UNLOCKED,
    DOCUMENT_WORKFLOW_UPDATED,
    TASK_CLAIMED,
    TASK_COMPLETED,
    FORM_SUBMITTED
}
